# Домашнее задание к уроку 1: Основы PyTorch


## Цель задания

Закрепить навыки работы с тензорами PyTorch, изучить основные операции и
научиться решать практические задачи.

## Задание 1: Создание и манипуляции с тензорами (25 баллов)

Создайте файл `homework_tensors.py` и выполните следующие задачи:

### 1.1 Создание тензоров (7 баллов)



In [3]:
import torch
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
tensor1 = torch.rand(3, 4)
tensor1

tensor([[0.6483, 0.0419, 0.1381, 0.4846],
        [0.3143, 0.4741, 0.8576, 0.1060],
        [0.0164, 0.2802, 0.4294, 0.5541]])

In [4]:
# - Тензор размером 2x3x4, заполненный нулями
tensor2 = torch.zeros(2, 3, 4)
tensor2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [5]:
# - Тензор размером 5x5, заполненный единицами
tensor3 = torch.ones(5, 5)
tensor3

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
tensor4 = torch.arange(16).reshape(4, 4)
tensor4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


### 1.2 Операции с тензорами (6 баллов)


In [7]:
# Дано: тензор A размером 3x4 и тензор B размером 4x3
A = torch.rand(3, 4)
B = torch.rand(4, 3)
print(A,B,sep='\n')


tensor([[0.3538, 0.1728, 0.1918, 0.5809],
        [0.8407, 0.7618, 0.1958, 0.0687],
        [0.3222, 0.3745, 0.5559, 0.7644]])
tensor([[0.6575, 0.3921, 0.8896],
        [0.8264, 0.1860, 0.8253],
        [0.7550, 0.9768, 0.5453],
        [0.4480, 0.2685, 0.5047]])


In [8]:
# Выполните:
# - Транспонирование тензора A
A_transposed = A.T
A_transposed

tensor([[0.3538, 0.8407, 0.3222],
        [0.1728, 0.7618, 0.3745],
        [0.1918, 0.1958, 0.5559],
        [0.5809, 0.0687, 0.7644]])

In [9]:
# - Матричное умножение A и B
A_matmul_B = A @ B
A_matmul_B

tensor([[0.7805, 0.5142, 0.8551],
        [1.3610, 0.6811, 1.5181],
        [1.2835, 0.9442, 1.2846]])

In [10]:
# - Поэлементное умножение A и транспонированного B
elements_mult = A * B.T
elements_mult

tensor([[0.2326, 0.1428, 0.1448, 0.2603],
        [0.3297, 0.1417, 0.1912, 0.0184],
        [0.2866, 0.3091, 0.3031, 0.3858]])

In [11]:
# - Вычислите сумму всех элементов тензора A
sum_A = torch.sum(A)
sum_A

tensor(5.1833)


### 1.3 Индексация и срезы (6 баллов)


In [12]:
# Создайте тензор размером 5x5x5
tensor5 = torch.rand(5,5,5)
tensor5

tensor([[[0.2589, 0.7041, 0.1545, 0.5488, 0.0616],
         [0.1452, 0.2080, 0.4992, 0.3724, 0.7027],
         [0.3027, 0.0044, 0.7243, 0.2714, 0.2760],
         [0.6942, 0.1006, 0.0656, 0.4901, 0.8155],
         [0.3874, 0.6409, 0.7620, 0.9448, 0.6151]],

        [[0.6466, 0.0025, 0.2674, 0.6979, 0.6569],
         [0.3767, 0.0866, 0.1923, 0.3814, 0.3939],
         [0.5314, 0.0658, 0.5891, 0.1930, 0.0870],
         [0.4728, 0.9274, 0.5472, 0.4253, 0.3097],
         [0.2905, 0.2974, 0.3305, 0.0554, 0.4591]],

        [[0.5621, 0.7826, 0.2674, 0.4707, 0.0391],
         [0.8120, 0.7812, 0.0037, 0.3432, 0.1022],
         [0.3419, 0.6540, 0.6632, 0.3700, 0.7478],
         [0.1073, 0.1235, 0.3159, 0.1390, 0.3689],
         [0.2139, 0.0878, 0.4601, 0.7415, 0.3915]],

        [[0.4570, 0.6192, 0.7280, 0.6863, 0.5941],
         [0.1190, 0.6416, 0.4611, 0.8967, 0.7575],
         [0.0493, 0.2308, 0.2171, 0.4998, 0.6841],
         [0.2940, 0.4543, 0.7227, 0.0375, 0.7611],
         [0.0613, 0.8315,

In [13]:
# Извлеките:
# - Первую строку
first_row = tensor5[0, 0, :]
first_row

tensor([0.2589, 0.7041, 0.1545, 0.5488, 0.0616])

In [14]:
# - Последний столбец
last_col = tensor5[:, :, -1]
last_col

tensor([[0.0616, 0.7027, 0.2760, 0.8155, 0.6151],
        [0.6569, 0.3939, 0.0870, 0.3097, 0.4591],
        [0.0391, 0.1022, 0.7478, 0.3689, 0.3915],
        [0.5941, 0.7575, 0.6841, 0.7611, 0.3322],
        [0.9035, 0.1023, 0.1820, 0.9477, 0.7710]])

In [15]:
# - Подматрицу размером 2x2 из центра тензора
center_2x2 = tensor5[2:4, 2:4, 2:4]
center_2x2

tensor([[[0.6632, 0.3700],
         [0.3159, 0.1390]],

        [[0.2171, 0.4998],
         [0.7227, 0.0375]]])

In [16]:
# - Все элементы с четными индексами
even_idx = tensor5[::2, ::2, ::2]
even_idx

tensor([[[0.2589, 0.1545, 0.0616],
         [0.3027, 0.7243, 0.2760],
         [0.3874, 0.7620, 0.6151]],

        [[0.5621, 0.2674, 0.0391],
         [0.3419, 0.6632, 0.7478],
         [0.2139, 0.4601, 0.3915]],

        [[0.9210, 0.0447, 0.9035],
         [0.2701, 0.1962, 0.1820],
         [0.9063, 0.9132, 0.7710]]])


### 1.4 Работа с формами (6 баллов)


In [17]:
# Создайте тензор размером 24 элемента
tensor6 = torch.rand(24)
tensor6

tensor([0.3455, 0.2708, 0.2131, 0.0037, 0.3055, 0.4520, 0.3894, 0.5443, 0.4869,
        0.1730, 0.5290, 0.4646, 0.0980, 0.2567, 0.2781, 0.7244, 0.1494, 0.9510,
        0.9958, 0.3514, 0.7480, 0.5923, 0.0516, 0.4512])

In [18]:
# Преобразуйте его в формы:
# - 2x12
shape_2x12 = tensor6.view(2, 12)
shape_2x12

tensor([[0.3455, 0.2708, 0.2131, 0.0037, 0.3055, 0.4520, 0.3894, 0.5443, 0.4869,
         0.1730, 0.5290, 0.4646],
        [0.0980, 0.2567, 0.2781, 0.7244, 0.1494, 0.9510, 0.9958, 0.3514, 0.7480,
         0.5923, 0.0516, 0.4512]])

In [19]:
# - 3x8
shape_3x8 = tensor6.view(3, 8)
shape_3x8

tensor([[0.3455, 0.2708, 0.2131, 0.0037, 0.3055, 0.4520, 0.3894, 0.5443],
        [0.4869, 0.1730, 0.5290, 0.4646, 0.0980, 0.2567, 0.2781, 0.7244],
        [0.1494, 0.9510, 0.9958, 0.3514, 0.7480, 0.5923, 0.0516, 0.4512]])

In [20]:
# - 4x6
shape_4x6 = tensor6.view(4, 6)
shape_4x6

tensor([[0.3455, 0.2708, 0.2131, 0.0037, 0.3055, 0.4520],
        [0.3894, 0.5443, 0.4869, 0.1730, 0.5290, 0.4646],
        [0.0980, 0.2567, 0.2781, 0.7244, 0.1494, 0.9510],
        [0.9958, 0.3514, 0.7480, 0.5923, 0.0516, 0.4512]])

In [21]:
# - 2x3x4
shape_2x3x4 = tensor6.view(2, 3, 4)
shape_2x3x4

tensor([[[0.3455, 0.2708, 0.2131, 0.0037],
         [0.3055, 0.4520, 0.3894, 0.5443],
         [0.4869, 0.1730, 0.5290, 0.4646]],

        [[0.0980, 0.2567, 0.2781, 0.7244],
         [0.1494, 0.9510, 0.9958, 0.3514],
         [0.7480, 0.5923, 0.0516, 0.4512]]])

In [22]:
# - 2x2x2x3
shape_2x2x2x3 = tensor6.view(2, 2, 2, 3)
shape_2x2x2x3

tensor([[[[0.3455, 0.2708, 0.2131],
          [0.0037, 0.3055, 0.4520]],

         [[0.3894, 0.5443, 0.4869],
          [0.1730, 0.5290, 0.4646]]],


        [[[0.0980, 0.2567, 0.2781],
          [0.7244, 0.1494, 0.9510]],

         [[0.9958, 0.3514, 0.7480],
          [0.5923, 0.0516, 0.4512]]]])



## Задание 2: Автоматическое дифференцирование (25 баллов)

Создайте файл `homework_autograd.py`:

### 2.1 Простые вычисления с градиентами (8 баллов)

In [23]:
# Создайте тензоры x, y, z с requires_grad=True
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = torch.tensor(3.0, requires_grad=True)
# Вычислите функцию: f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z
f = x**2 + y**2 + z**2 + 2*x*y*z
f.backward()
# Найдите градиенты по всем переменным
print(f"df/dx={x.grad.item()}, df/dy={y.grad.item()}, df/dz={z.grad.item()}")
# Проверьте результат аналитически
# df/dx = 2x + 2yz = 14, df/dy=2y+2xz = 10, df/dz=2z+2xy = 10

df/dx=14.0, df/dy=10.0, df/dz=10.0




### 2.2 Градиент функции потерь (9 баллов)


In [24]:
# Реализуйте функцию MSE (Mean Squared Error):
# MSE = (1/n) * Σ(y_pred - y_true)^2
def mse(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

x_data = torch.randn(10, requires_grad=False)
x_data

tensor([ 1.3821, -0.4053, -1.1577,  0.0047, -0.5359,  0.6307,  0.7431,  0.3708,
         1.3253, -0.0980])

In [25]:
y_true = 3 + 3*x_data + torch.randn(10) * 0.1 # добавляем шум
y_true

tensor([ 7.2537,  1.7028, -0.6363,  2.8760,  1.5277,  4.9705,  5.1385,  4.1824,
         6.9836,  2.8179])

In [26]:
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# где y_pred = w * x + b (линейная функция)
y_pred = w * x_data + b
loss = mse(y_pred, y_true)
loss.backward()
# Найдите градиенты по w и b
print(f"dMSE/dw={w.grad.item()}, dMSE/db={b.grad.item()}")

dMSE/dw=-5.349992752075195, dMSE/db=-7.363372802734375




### 2.3 Цепное правило (8 баллов)


In [27]:
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
x_var = torch.tensor(1.0, requires_grad=True)
f = torch.sin(x_var ** 2 + 1)
f.backward()
# Найдите градиент df/dx
print(" Градиент df/dx:", x_var.grad.item())
# Проверьте результат с помощью torch.autograd.grad
grad = torch.autograd.grad(torch.sin(x_var ** 2 + 1), x_var)[0]
print("Проверка через autograd.grad:", grad.item())

 Градиент df/dx: -0.832293689250946
Проверка через autograd.grad: -0.832293689250946


## Задание 3: Сравнение производительности CPU vs CUDA (20 баллов)

Создайте файл `homework_performance.py`:

### 3.1 Подготовка данных (5 баллов)

In [28]:
import time
import torch
device_cpu = torch.device("cpu")
device_gpu = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Создайте большие матрицы размеров:
# - 64 x 1024 x 1024
# - 128 x 512 x 512
# - 256 x 256 x 256
# Заполните их случайными числами
sizes = [(64, 1024, 1024), (128, 512, 512), (256, 256, 256)]
matrices = [torch.randn(*size) for size in sizes]

### 3.2 Функция измерения времени (5 баллов)

``` python
# Создайте функцию для измерения времени выполнения операций
# Используйте torch.cuda.Event() для точного измерения на GPU
# Используйте time.time() для измерения на CPU
```

In [29]:
# Создайте функцию для измерения времени выполнения операций
def measure_time(op, x_cpu, x_gpu):
    # CPU
    # Используйте time.time() для измерения на CPU
    start_cpu = time.time()
    op(x_cpu)
    cpu_time = (time.time() - start_cpu) * 1000  # в мс

    # GPU
    # Используйте torch.cuda.Event() для точного измерения на GPU
    if torch.cuda.is_available():
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)

        start_event.record()
        op(x_gpu)
        end_event.record()
        torch.cuda.synchronize()
        gpu_time = start_event.elapsed_time(end_event)  # в мс
    else:
        gpu_time = None

    return cpu_time, gpu_time

### 3.3 Сравнение операций (10 баллов)

``` python
# Сравните время выполнения следующих операций на CPU и CUDA:
# - Матричное умножение (torch.matmul)
# - Поэлементное сложение
# - Поэлементное умножение
# - Транспонирование
# - Вычисление суммы всех элементов

# Для каждой операции:
# 1. Измерьте время на CPU
# 2. Измерьте время на GPU (если доступен)
# 3. Вычислите ускорение (speedup)
# 4. Выведите результаты в табличном виде
```

In [30]:
operations = {
    "Матричное умножение": lambda x: torch.matmul(x, x.transpose(-1, -2)),
    "Сложение": lambda x: x + x,
    "Умножение": lambda x: x * x,
    "Транспонирование": lambda x: x.transpose(-1, -2),
    "Сумма элементов": lambda x: x.sum(),
}

In [31]:
print(f"{'Операция':20} | {'CPU (мс)':>8} | {'GPU (мс)':>8} | {'Ускорение':>10}")
print("-"*55)
for op_name, op_func in operations.items():
    x_cpu = matrices[0].to(device_cpu)
    x_gpu = matrices[0].to(device_gpu)
    cpu_t, gpu_t = measure_time(op_func, x_cpu, x_gpu)
    speedup = (cpu_t / gpu_t) if gpu_t else None
    print(f"{op_name:20} | {cpu_t:8.1f} | {gpu_t or 0:8.1f} | {speedup or '-':>10}")

Операция             | CPU (мс) | GPU (мс) |  Ускорение
-------------------------------------------------------
Матричное умножение  |   1358.8 |    171.3 | 7.932106587793706
Сложение             |    162.2 |     37.7 | 4.298346779690925
Умножение            |    142.0 |     28.5 | 4.977008424516065
Транспонирование     |      0.0 |      0.0 | 1.8792547669294761
Сумма элементов      |     21.8 |     35.3 | 0.6173117846548816


In [32]:
for op_name, op_func in operations.items():
    x_cpu = matrices[1].to(device_cpu)
    x_gpu = matrices[1].to(device_gpu)
    cpu_t, gpu_t = measure_time(op_func, x_cpu, x_gpu)
    speedup = (cpu_t / gpu_t) if gpu_t else None
    print(f"{op_name:20} | {cpu_t:8.1f} | {gpu_t or 0:8.1f} | {speedup or '-':>10}")

Матричное умножение  |    344.8 |     13.3 | 26.01471376420059
Сложение             |     76.1 |      1.2 | 64.55767739561291
Умножение            |     85.1 |      1.2 | 71.32445647835958
Транспонирование     |      0.0 |      0.0 | 1.240581961428756
Сумма элементов      |     11.2 |      0.7 | 17.11631746664937


In [33]:
for op_name, op_func in operations.items():
    x_cpu = matrices[2].to(device_cpu)
    x_gpu = matrices[2].to(device_gpu)
    cpu_t, gpu_t = measure_time(op_func, x_cpu, x_gpu)
    speedup = (cpu_t / gpu_t) if gpu_t else None
    print(f"{op_name:20} | {cpu_t:8.1f} | {gpu_t or 0:8.1f} | {speedup or '-':>10}")

Матричное умножение  |    119.5 |      3.6 | 32.82061258584511
Сложение             |     33.8 |      0.6 | 55.223756831872194
Умножение            |     36.7 |      0.6 | 59.51536056535824
Транспонирование     |      0.0 |      0.0 | 0.908170246072313
Сумма элементов      |      4.8 |      0.3 | 14.516578196701536


### 3.4 Анализ результатов (5 баллов)

``` python
# Проанализируйте результаты:
# - Какие операции получают наибольшее ускорение на GPU?
# - Почему некоторые операции могут быть медленнее на GPU?
# - Как размер матриц влияет на ускорение?
# - Что происходит при передаче данных между CPU и GPU?
```

### Операции с большим числом независимых поэлементных вычислений (умножения, сложение) показывают наибольшее ускорение на GPU.
### Операции с небольшими матрицами или интенсивным доступом к памяти (Сумма элементов или транспонирование по тестам) могут быть медленнее на GPU из-за расходов на копирование данных и инициализацию.
### Чем больше размер матрицы, тем выше ускорение на GPU.
### При передаче данных между CPU и GPU происходит задержка — всегда старайтесь минимизировать пересылки.